services:
    smarter.ezcomponents.language_switcher:
        class: SmarterSolutions\EzComponents\EzLanguageSwitcherBundle\Language\LanguageSwitcherService
        arguments:
            - @service_container
        scope: request
